namespace URG_Console;

/// <summary>
/// Contains application-wide constants for magic numbers and strings.
/// </summary>
public static class Constants
{
    #region Article Type Thresholds
    /// <summary>
    /// Maximum character count for "Інф. повідомлення" (Information message).
    /// </summary>
    public const int ArticleTypeInfoMessageMaxChars = 1399;

    /// <summary>
    /// Maximum character count for "Розш. інф. повідомлення" (Extended information message).
    /// </summary>
    public const int ArticleTypeExtendedInfoMessageMaxChars = 4999;

    /// <summary>
    /// Minimum character count for "Коментар" (Comment).
    /// </summary>
    public const int ArticleTypeCommentMinChars = 5000;
    #endregion

    #region Default Values
    /// <summary>
    /// Default date format when date cannot be parsed.
    /// </summary>
    public const string DefaultDate = "**.**.****";

    /// <summary>
    /// Default header text when header cannot be set.
    /// </summary>
    public const string DefaultHeader = "Unknown";

    /// <summary>
    /// Default article type when type cannot be determined.
    /// </summary>
    public const string DefaultArticleType = "N/A";

    /// <summary>
    /// Error article type.
    /// </summary>
    public const string ErrorArticleType = "Error";

    /// <summary>
    /// Default header text when header setting fails.
    /// </summary>
    public const string DefaultHeaderNotSet = "[Header not set]";
    #endregion

    #region Article Type Names
    /// <summary>
    /// Article type name for information messages.
    /// </summary>
    public const string ArticleTypeInfoMessage = "Інф. повідомлення";

    /// <summary>
    /// Article type name for extended information messages.
    /// </summary>
    public const string ArticleTypeExtendedInfoMessage = "Розш. інф. повідомлення";

    /// <summary>
    /// Article type name for comments.
    /// </summary>
    public const string ArticleTypeComment = "Коментар";

    /// <summary>
    /// Exclusive article prefix text.
    /// </summary>
    public const string ArticleExclusivePrefix = "Ексклюзив";
    #endregion

    #region Table Dimensions
    /// <summary>
    /// Table cell width for column 0 (№з/п) in points (0.54 inches * 72).
    /// </summary>
    public const double TableCellWidthColumn0 = 0.54 * 72;

    /// <summary>
    /// Table cell width for column 1 (Дата) in points (1.21 inches * 72).
    /// </summary>
    public const double TableCellWidthColumn1 = 1.21 * 72;

    /// <summary>
    /// Table cell width for column 2 (Заголовок) in points (3.25 inches * 72).
    /// </summary>
    public const double TableCellWidthColumn2 = 3.25 * 72;

    /// <summary>
    /// Table cell width for column 3 (Жанр) in points (1.19 inches * 72).
    /// </summary>
    public const double TableCellWidthColumn3 = 1.19 * 72;

    /// <summary>
    /// Table cell width for column 4 (Кільк. знаків) in points (0.82 inches * 72).
    /// </summary>
    public const double TableCellWidthColumn4 = 0.82 * 72;

    /// <summary>
    /// Table header row height in points (0.39 inches * 72).
    /// </summary>
    public const double TableHeaderRowHeight = 0.39 * 72;
    #endregion

    #region Roman Numerals
    /// <summary>
    /// Roman numerals for week numbers (1-5).
    /// </summary>
    public static readonly string[] RomanNumerals = { "I", "II", "III", "IV", "V" };

    /// <summary>
    /// Minimum valid week number.
    /// </summary>
    public const int MinWeekNumber = 1;

    /// <summary>
    /// Maximum valid week number.
    /// </summary>
    public const int MaxWeekNumber = 5;
    #endregion

    #region Process Names
    /// <summary>
    /// Microsoft Word process name.
    /// </summary>
    public const string WordProcessName = "WINWORD";
    #endregion

    #region File Name Patterns
    /// <summary>
    /// Pattern to identify multi-article files (contains "1+").
    /// </summary>
    public const string MultiArticleFilePattern = "1+";

    /// <summary>
    /// Prefix for auto-generated report files that should be ignored during parsing.
    /// </summary>
    public const string AutoGeneratedFilePrefix = "AUTO_";
    #endregion

    #region Console Message Prefixes
    /// <summary>
    /// Console message prefix for ArticleParser service.
    /// </summary>
    public const string ConsolePrefixArticleParser = "[ArticleParser]";

    /// <summary>
    /// Console message prefix for DocumentParser service.
    /// </summary>
    public const string ConsolePrefixDocumentParser = "[DocumentParser]";

    /// <summary>
    /// Console message prefix for WordReportBuilder service.
    /// </summary>
    public const string ConsolePrefixWordReportBuilder = "[WordReportBuilder]";

    /// <summary>
    /// Console message prefix for ReportDateCalculator service.
    /// </summary>
    public const string ConsolePrefixReportDateCalculator = "[ReportDateCalculator]";

    /// <summary>
    /// Console message prefix for ReportHeaderBuilder service.
    /// </summary>
    public const string ConsolePrefixReportHeaderBuilder = "[ReportHeaderBuilder]";

    /// <summary>
    /// Console message prefix for ArticleDisplayService service.
    /// </summary>
    public const string ConsolePrefixArticleDisplayService = "[ArticleDisplayService]";

    /// <summary>
    /// Console message prefix for Program entry point.
    /// </summary>
    public const string ConsolePrefixProgram = "[Program]";
    #endregion

    #region Document Parsing
    /// <summary>
    /// Maximum number of characters to search for the first hyperlink in document header area.
    /// Used to validate that the hyperlink is in the article header, not in the body.
    /// This character-based approach works regardless of how many paragraphs (like file names) appear before the article header.
    /// </summary>
    public const int HeaderValidationCharacterLimit = 150;
    #endregion
}

