using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using URG_Console.Interfaces;
using Xceed.Words.NET;

namespace URG_Console.Services;

/// <summary>
/// Service for parsing documents to extract article sources.
/// </summary>
public class DocumentParser : IDocumentParser
{
    /// <inheritdoc/>
    public async Task<List<ArticleSource>> ParseDocumentsInDirectoryAsync(string directoryPath)
    {
        string[] filePaths = await GetDocsFilePathAsync(directoryPath);
        return await ExtractLinksFromDocumentsAsync(filePaths);
    }

    /// <summary>
    /// Gets all Word document file paths from the specified directory.
    /// Filters out auto-generated report files (starting with "AUTO_") and temporary files.
    /// </summary>
    /// <param name="path">The directory path to search.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains an array of file paths.</returns>
    /// <exception cref="DirectoryNotFoundException">Thrown when the specified directory does not exist.</exception>
    private static async Task<string[]> GetDocsFilePathAsync(string path)
    {
        return await Task.Run(() =>
        {
            if (!Directory.Exists(path))
                throw new DirectoryNotFoundException($"{Constants.ConsolePrefixDocumentParser} Selected directory doesn't exist!");

            var allWordFiles = Directory.GetFiles(path, "*.docx")
                .Concat(Directory.GetFiles(path, "*.doc"))
                .ToList();

            var skippedFiles = new List<string>();
            var wordFiles = allWordFiles
                .Where(file =>
                {
                    string fileName = Path.GetFileName(file);

                    // Skip temporary files
                    if (file.Contains("~$"))
                        return false;

                    // Skip auto-generated report files
                    if (fileName.StartsWith(Constants.AutoGeneratedFilePrefix, StringComparison.OrdinalIgnoreCase))
                    {
                        skippedFiles.Add(fileName);
                        return false;
                    }

                    return true;
                })
                .OrderBy(file => new FileInfo(file).LastWriteTimeUtc)
                .ToArray();

            // Log skipped files
            if (skippedFiles.Count > 0)
            {
                foreach (var skippedFile in skippedFiles)
                {
                    Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {skippedFile}");
                    Console.WriteLine("Skipped (auto-generated report file)");
                }
            }

            return wordFiles;
        });
    }

    /// <summary>
    /// Extracts article source links from the specified document files.
    /// </summary>
    /// <param name="filePaths">Array of file paths to process.</param>
    /// <returns>A task that represents the asynchronous operation. The task result contains a list of article sources.</returns>
    /// <exception cref="ArgumentNullException">Thrown when filePaths is null.</exception>
    private static async Task<List<ArticleSource>> ExtractLinksFromDocumentsAsync(string[] filePaths)
    {
        if (filePaths == null)
            throw new ArgumentNullException(nameof(filePaths), "Null filePaths array was passed to DocumentParser!");

        var articleSources = new List<ArticleSource>();

        // Process files in parallel for better performance
        var tasks = filePaths.Select(async filePath =>
        {
            await ProcessFileAsync(filePath, articleSources);
        });

        await Task.WhenAll(tasks);

        Console.WriteLine($"\n{Constants.ConsolePrefixDocumentParser} Successfully extracted article sources from documents: {articleSources.Count}");
        return articleSources;
    }

    /// <summary>
    /// Processes a single document file to extract article sources.
    /// </summary>
    /// <param name="filePath">The path to the document file.</param>
    /// <param name="articleSources">The list to add extracted article sources to.</param>
    /// <returns>A task that represents the asynchronous operation. Returns true if successful, false otherwise.</returns>
    private static async Task<bool> ProcessFileAsync(string filePath, List<ArticleSource> articleSources)
    {
        return await Task.Run(() =>
        {
            try
            {
                using var doc = DocX.Load(filePath);
                if (!doc.Hyperlinks.Exists(HasUkrinformLinks))
                {
                    lock (articleSources)
                    {
                        articleSources.Add(new ArticleSource("", filePath));
                    }
                    Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                    Console.WriteLine("No Ukrinform links were found in the file!");
                    return false;
                }

                string fileName = Path.GetFileName(filePath);
                if (fileName.Contains(Constants.MultiArticleFilePattern))
                {
                    return ProcessMultiArticleFile(doc, filePath, articleSources, fileName);
                }
                else
                {
                    return ProcessSingleArticleFile(doc, filePath, articleSources);
                }
            }
            catch (Exception ex)
            {
                // Handle unexpected errors (file corruption, access issues, etc.)
                lock (articleSources)
                {
                    articleSources.Add(new ArticleSource("", filePath));
                }
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} Unexpected error: {ex.Message}");
                return false;
            }
        });
    }

    /// <summary>
    /// Processes a multi-article file (file name contains "1+" pattern).
    /// </summary>
    /// <param name="doc">The loaded Word document.</param>
    /// <param name="filePath">The path to the document file.</param>
    /// <param name="articleSources">The list to add extracted article sources to.</param>
    /// <param name="fileName">The name of the file.</param>
    /// <returns>True if processing succeeded, false if validation failed.</returns>
    private static bool ProcessMultiArticleFile(DocX doc, string filePath, List<ArticleSource> articleSources, string fileName)
    {
        try
        {
            int numOfAdditionalArticles = ExtractAdditionalArticlesCount(fileName);
            var ukrinformLinks = doc.Hyperlinks.FindAll(HasUkrinformLinks);

            if (numOfAdditionalArticles + 1 > ukrinformLinks.Count)
            {
                lock (articleSources)
                {
                    articleSources.Add(new ArticleSource("", filePath));
                }
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                Console.WriteLine($"Number of articles declared in the filename [1+{numOfAdditionalArticles}] is invalid!\nYou have less article links in the file than declared!");
                return false; // Invalid article count
            }

            foreach (var link in ukrinformLinks)
            {
                if (!AddArticleSource(articleSources, link.Uri?.ToString(), filePath))
                {
                    return false; // Duplicate or invalid link (error already logged in AddArticleSource)
                }
            }

            return true;
        }
        catch (Exception ex)
        {
            // Handle parsing errors (e.g., invalid filename format)
            lock (articleSources)
            {
                articleSources.Add(new ArticleSource("", filePath));
            }
            Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
            Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} Error parsing multi-article file: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Processes a single-article file.
    /// </summary>
    /// <param name="doc">The loaded Word document.</param>
    /// <param name="filePath">The path to the document file.</param>
    /// <param name="articleSources">The list to add extracted article sources to.</param>
    /// <returns>True if processing succeeded, false if validation failed.</returns>
    private static bool ProcessSingleArticleFile(DocX doc, string filePath, List<ArticleSource> articleSources)
    {
        try
        {
            var firstLink = FindFirstHyperlinkInHeaderArea(doc);

            if (firstLink == null)
            {
                lock (articleSources)
                {
                    articleSources.Add(new ArticleSource("", filePath));
                }
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                Console.WriteLine("No Ukrinform hyperlink found in the document header area!");
                return false;
            }

            string? linkUri = firstLink.Uri?.ToString();

            if (linkUri is null)
            {
                lock (articleSources)
                {
                    articleSources.Add(new ArticleSource("", filePath));
                }
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                Console.WriteLine("Null URL was detected when tried to add first document hyperlink to the list!\n(You might have broken saved file. Try to modify, resave it and try again)");
                return false; // Null URL
            }

            if (linkUri.Contains("ukrinform"))
            {
                return AddArticleSource(articleSources, linkUri, filePath);
            }
            else
            {
                lock (articleSources)
                {
                    articleSources.Add(new ArticleSource("", filePath));
                }
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                Console.WriteLine("First hyperlink in header area is not Ukrinform related!");
                return false; // Not a Ukrinform link
            }
        }
        catch (Exception ex)
        {
            // Handle unexpected errors (e.g., no hyperlinks in document)
            lock (articleSources)
            {
                articleSources.Add(new ArticleSource("", filePath));
            }
            Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
            Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} Unexpected error: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Finds the first Ukrinform hyperlink in the document header area based on document reading order.
    /// Uses a general approach: iterates through paragraphs in document order and identifies which hyperlinks
    /// belong to each paragraph, then returns the first one found within the header character limit.
    /// This works for any document structure regardless of content, formatting, or number of preceding elements.
    /// </summary>
    /// <param name="doc">The loaded Word document.</param>
    /// <returns>The first Ukrinform hyperlink found within the header area (first N characters), or null if none found.</returns>
    private static Xceed.Document.NET.Hyperlink? FindFirstHyperlinkInHeaderArea(DocX doc)
    {
        // General strategy: 
        // 1. Iterate paragraphs in document reading order (this is the canonical order)
        // 2. For each paragraph, determine which hyperlinks belong to it
        // 3. Track cumulative character position
        // 4. Return the first hyperlink found within the header limit
        // This approach is structure-agnostic and works for any document layout

        var allUkrinformLinks = doc.Hyperlinks.FindAll(HasUkrinformLinks).ToList();

        if (allUkrinformLinks.Count == 0)
        {
            return null;
        }

        int cumulativeCharPosition = 0;
        var foundHyperlinks = new HashSet<Xceed.Document.NET.Hyperlink>();

        // Iterate through paragraphs in document reading order
        foreach (var paragraph in doc.Paragraphs)
        {
            // Stop searching if we've exceeded the header character limit
            if (cumulativeCharPosition >= Constants.HeaderValidationCharacterLimit)
            {
                break;
            }

            string paragraphText = paragraph.Text ?? string.Empty;
            int paragraphStartPosition = cumulativeCharPosition;
            int paragraphEndPosition = cumulativeCharPosition + paragraphText.Length;

            // Only examine the portion of the paragraph that's within our character limit
            // This handles cases where a paragraph spans the boundary
            int remainingCharsInLimit = Constants.HeaderValidationCharacterLimit - cumulativeCharPosition;
            string textToExamine = paragraphText;
            if (remainingCharsInLimit > 0 && paragraphText.Length > remainingCharsInLimit)
            {
                // Only check the portion within the limit
                textToExamine = paragraphText.Substring(0, remainingCharsInLimit);
            }
            else if (remainingCharsInLimit <= 0)
            {
                // We've already exceeded the limit, skip this paragraph
                break;
            }

            // Check each Ukrinform hyperlink to see if it belongs to this paragraph
            // A hyperlink belongs to a paragraph if its text or URI appears in the paragraph's content
            foreach (var hyperlink in allUkrinformLinks)
            {
                // Skip if we've already processed this hyperlink
                if (foundHyperlinks.Contains(hyperlink))
                    continue;

                string? linkUri = hyperlink.Uri?.ToString();
                if (string.IsNullOrEmpty(linkUri))
                    continue;

                // Determine if this hyperlink belongs to the current paragraph
                bool belongsToParagraph = false;
                int hyperlinkPositionInParagraph = -1;
                int hyperlinkLength = 0;

                // Check if hyperlink text appears in paragraph (most common case)
                string hyperlinkText = hyperlink.Text ?? string.Empty;
                if (!string.IsNullOrEmpty(hyperlinkText))
                {
                    int textIndex = textToExamine.IndexOf(hyperlinkText, StringComparison.OrdinalIgnoreCase);
                    if (textIndex >= 0)
                    {
                        belongsToParagraph = true;
                        hyperlinkPositionInParagraph = textIndex;
                        hyperlinkLength = hyperlinkText.Length;
                    }
                }

                // If not found by text, check if URI appears in paragraph (some docs show URLs as visible text)
                if (!belongsToParagraph)
                {
                    int uriIndex = textToExamine.IndexOf(linkUri, StringComparison.OrdinalIgnoreCase);
                    if (uriIndex >= 0)
                    {
                        belongsToParagraph = true;
                        hyperlinkPositionInParagraph = uriIndex;
                        hyperlinkLength = linkUri.Length;
                    }
                }

                // If hyperlink belongs to this paragraph, calculate its absolute position
                if (belongsToParagraph && hyperlinkPositionInParagraph >= 0)
                {
                    int absoluteHyperlinkStartPosition = paragraphStartPosition + hyperlinkPositionInParagraph;

                    // If hyperlink starts within the header limit, accept it
                    // This is the proper approach: if the first character is in the header area,
                    // the hyperlink belongs to the header, even if it extends slightly beyond
                    if (absoluteHyperlinkStartPosition < Constants.HeaderValidationCharacterLimit)
                    {
                        return hyperlink;
                    }

                    // Mark as found even if outside limit (for tracking)
                    foundHyperlinks.Add(hyperlink);
                }
            }

            // Move to next paragraph
            cumulativeCharPosition = paragraphEndPosition;
        }

        // No hyperlink found within the header area
        // Return null to indicate that no valid header hyperlink was found
        // This allows the caller to show an appropriate error message
        return null;
    }

    /// <summary>
    /// Adds an article source to the list, checking for duplicates.
    /// </summary>
    /// <param name="articleSources">The list of article sources.</param>
    /// <param name="link">The article link URL.</param>
    /// <param name="filePath">The path to the source file.</param>
    /// <returns>True if the article source was added successfully, false if it's a duplicate or invalid.</returns>
    private static bool AddArticleSource(List<ArticleSource> articleSources, string? link, string filePath)
    {
        lock (articleSources)
        {
            if (string.IsNullOrEmpty(link))
            {
                articleSources.Add(new ArticleSource("", filePath));
                return false; // Invalid link (shouldn't happen, but handled gracefully)
            }

            var potentialDuplicateArticle = articleSources.FirstOrDefault(x => x.Link == link);

            if (potentialDuplicateArticle != default(ArticleSource))
            {
                articleSources.Add(new ArticleSource("", filePath));
                Console.WriteLine($"{Constants.ConsolePrefixDocumentParser} File: {Path.GetFileName(filePath)}");
                Console.WriteLine($"Same link has already been seen in another file! ({Path.GetFileName(potentialDuplicateArticle.FilePath)})");
                return false;
            }

            articleSources.Add(new ArticleSource(link, filePath));
            return true;
        }
    }

    /// <summary>
    /// Extracts the number of additional articles from a multi-article filename (e.g., "1+2" returns 2).
    /// </summary>
    /// <param name="fileName">The filename containing the pattern.</param>
    /// <returns>The number of additional articles.</returns>
    private static int ExtractAdditionalArticlesCount(string fileName)
    {
        int startIndex = fileName.IndexOf('+') + 1;
        int endIndex = fileName.IndexOf('_', startIndex);
        return int.Parse(fileName[startIndex..endIndex]);
    }

    /// <summary>
    /// Checks if a hyperlink contains "ukrinform" in its URI.
    /// </summary>
    /// <param name="link">The hyperlink to check.</param>
    /// <returns>True if the link URI contains "ukrinform", otherwise false.</returns>
    private static bool HasUkrinformLinks(Xceed.Document.NET.Hyperlink link)
    {
        return link.Uri?.ToString().Contains("ukrinform") ?? false;
    }

}

